"""
Mock CBOM data -- stands in for Dev 1's scanner output during dev.

Once Dev 1's source-code/binary/container scanner is ready, it just
needs to emit a list of dicts shaped like SAMPLE_CBOM below (or the
CryptoArtefact dataclass) and everything downstream keeps working.
"""

SAMPLE_CBOM = [
    {
        "id": "art-001",
        "name": "api-gateway-tls-cert",
        "type": "certificate",
        "algorithm": "RSA-2048",
        "location": "services/api-gateway/tls/cert.pem",
        "key_length": 2048,
        "internet_facing": True,
        "data_classification": "PII",
        "data_volume_gb": 120.0,
        "used_by": ["mobile-app", "partner-api", "web-frontend"],
        "first_seen": "2021-03-01",
    },
    {
        "id": "art-002",
        "name": "auth-service-jwt-signing-key",
        "type": "key",
        "algorithm": "ECDSA-P256",
        "location": "services/auth/keys/jwt_signing.pem",
        "key_length": 256,
        "internet_facing": True,
        "data_classification": "PII",
        "data_volume_gb": 5.0,
        "used_by": ["mobile-app", "web-frontend", "partner-api", "internal-admin"],
        "first_seen": "2020-11-12",
    },
    {
        "id": "art-003",
        "name": "payments-db-encryption",
        "type": "algorithm",
        "algorithm": "AES-256-GCM",
        "location": "services/payments/db/encryption.py",
        "key_length": 256,
        "internet_facing": False,
        "data_classification": "financial",
        "data_volume_gb": 850.0,
        "used_by": ["billing-service", "reporting-service"],
        "first_seen": "2019-06-20",
    },
    {
        "id": "art-004",
        "name": "legacy-file-transfer-cipher",
        "type": "algorithm",
        "algorithm": "3DES",
        "location": "services/legacy-ftp/cipher.c",
        "key_length": 168,
        "internet_facing": False,
        "data_classification": "internal",
        "data_volume_gb": 40.0,
        "used_by": ["batch-processor"],
        "first_seen": "2015-01-10",
    },
    {
        "id": "art-005",
        "name": "openssl-libcrypto",
        "type": "library",
        "algorithm": "RSA-4096",
        "location": "vendor/openssl/1.1.1",
        "key_length": 4096,
        "internet_facing": True,
        "data_classification": "financial",
        "data_volume_gb": 300.0,
        "used_by": ["payments-service", "auth-service", "api-gateway", "partner-api"],
        "first_seen": "2018-08-04",
        "library_name": "openssl",
        "library_version": "1.1.0",   # deliberately vulnerable version -> triggers CVE findings
    },
    {
        "id": "art-006",
        "name": "session-key-exchange",
        "type": "protocol",
        "algorithm": "ECDH-P384",
        "location": "services/session/handshake.go",
        "key_length": 384,
        "internet_facing": True,
        "data_classification": "PII",
        "data_volume_gb": 60.0,
        "used_by": ["mobile-app", "web-frontend"],
        "first_seen": "2022-02-18",
    },
    {
        "id": "art-007",
        "name": "internal-log-signing-key",
        "type": "key",
        "algorithm": "DSA-2048",
        "location": "services/audit/log_signer.py",
        "key_length": 2048,
        "internet_facing": False,
        "data_classification": "internal",
        "data_volume_gb": 15.0,
        "used_by": ["audit-service"],
        "first_seen": "2017-09-01",
    },
    {
        "id": "art-008",
        "name": "next-gen-vpn-handshake",
        "type": "protocol",
        "algorithm": "ML-KEM-768",
        "location": "services/vpn/handshake_pqc.rs",
        "key_length": 768,
        "internet_facing": True,
        "data_classification": "financial",
        "data_volume_gb": 25.0,
        "used_by": ["remote-access-gateway"],
        "first_seen": "2025-09-01",
    },
    {
        "id": "art-009",
        "name": "config-secrets-cipher",
        "type": "algorithm",
        "algorithm": "AES-128-CBC",
        "location": "infra/config/secrets.yaml.enc",
        "key_length": 128,
        "internet_facing": False,
        "data_classification": "internal",
        "data_volume_gb": 2.0,
        "used_by": ["ci-cd-pipeline"],
        "first_seen": "2020-04-22",
    },
    {
        "id": "art-010",
        "name": "partner-api-mutual-tls",
        "type": "certificate",
        "algorithm": "ECDSA-P256",
        "location": "services/partner-api/tls/client_cert.pem",
        "key_length": 256,
        "internet_facing": True,
        "data_classification": "financial",
        "data_volume_gb": 90.0,
        "used_by": ["partner-api"],
        "first_seen": "2021-12-05",
    },
    {
        "id": "art-011",
        "name": "code-signing-key",
        "type": "key",
        "algorithm": "RSA-3072",
        "location": "release/signing/codesign.key",
        "key_length": 3072,
        "internet_facing": False,
        "data_classification": "internal",
        "data_volume_gb": 1.0,
        "used_by": ["release-pipeline"],
        "first_seen": "2019-01-15",
    },
    {
        "id": "art-012",
        "name": "document-signature-service",
        "type": "algorithm",
        "algorithm": "ML-DSA-65",
        "location": "services/edoc/sign.py",
        "key_length": 65,
        "internet_facing": True,
        "data_classification": "PII",
        "data_volume_gb": 12.0,
        "used_by": ["edoc-service"],
        "first_seen": "2026-01-10",
    },
    # --- Certificate with expiry / self-signed / weak-signature issues ---
    {
        "id": "art-013",
        "name": "internal-admin-tls-cert",
        "type": "certificate",
        "algorithm": "RSA-2048",
        "location": "services/internal-admin/tls/cert.pem",
        "key_length": 2048,
        "internet_facing": False,
        "data_classification": "internal",
        "data_volume_gb": 3.0,
        "used_by": ["internal-admin"],
        "first_seen": "2019-05-01",
        "issuer": "Internal-CA",
        "expiry_date": "2025-12-01",   # already expired relative to scan date
        "self_signed": True,
        "signature_algorithm": "SHA1WITHRSA",
    },
    # --- Low-confidence heuristic match: keyword hit only, not a resolved call site ---
    {
        "id": "art-014",
        "name": "possible-des-reference-in-comment",
        "type": "algorithm",
        "algorithm": "DES",
        "location": "services/legacy-ftp/README.md",
        "key_length": 56,
        "internet_facing": False,
        "data_classification": "internal",
        "data_volume_gb": 0.0,
        "used_by": [],
        "first_seen": "2015-01-10",
        "confidence": "low",
    },
    # --- Duplicate occurrences of the SAME weak pattern across many files,
    #     used to demonstrate deduplication/aggregation. All three share
    #     name+type+algorithm with art-009 and should merge into one
    #     artefact with occurrence_count=3 once deduplicate() runs. ---
    {
        "id": "art-009b",
        "name": "config-secrets-cipher",
        "type": "algorithm",
        "algorithm": "AES-128-CBC",
        "location": "infra/config/staging_secrets.yaml.enc",
        "key_length": 128,
        "internet_facing": False,
        "data_classification": "internal",
        "data_volume_gb": 1.5,
        "used_by": ["ci-cd-pipeline"],
        "first_seen": "2020-05-01",
    },
    {
        "id": "art-009c",
        "name": "config-secrets-cipher",
        "type": "algorithm",
        "algorithm": "AES-128-CBC",
        "location": "infra/config/prod_secrets.yaml.enc",
        "key_length": 128,
        "internet_facing": False,
        "data_classification": "internal",
        "data_volume_gb": 2.5,
        "used_by": ["ci-cd-pipeline", "release-pipeline"],
        "first_seen": "2020-06-01",
    },
]
